"use strict";
const assert = require("assert");
const config = require('../config.json');
assert(typeof config.LOGBAUDOTINTERFACE == "number");
assert(typeof config.PORT == "number");
assert(typeof config.TLN_SERVER_HOST == "string");
assert(typeof config.TLN_SERVER_PORT == "number");
assert(!config.LOCAL_NUMBER || typeof config.LOCAL_NUMBER == "number");
assert(typeof config.IDENTIFIER == "string");
assert(typeof config.CONNECT_TIMEOUT == "number");
module.exports = config;
